<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="generator" content="pandoc" />

        <meta name="author" content="Pu Fanyi" />
        <meta name="author" content="Zhang Kaichen" />
        <meta name="author" content="Shan Yi" />
        <meta name="author" content="Fu Yilin" />
        <meta name="author" content="Mu Yichen" />
    
        <meta name="date" content="2024-11-11" />
    
    <title>MH3510 Regression Analysis</title>

        <script src="DataAnalysis_files/header-attrs-2.29/header-attrs.js"></script>
        <script src="DataAnalysis_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="DataAnalysis_files/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet" />
        <script src="DataAnalysis_files/bootstrap-3.3.7/js/bootstrap.min.js"></script>
        <script src="DataAnalysis_files/navigation-1.1/tabsets.js"></script>
        <link href="DataAnalysis_files/readthedown-0.1/readthedown.css" rel="stylesheet" />
        <link href="DataAnalysis_files/readthedown-0.1/readthedown_fonts_embed.css" rel="stylesheet" />
        <script src="DataAnalysis_files/readthedown-0.1/readthedown.js"></script>
    
    
        <style type="text/css">code{white-space: pre;}</style>
    <style type="text/css">
      pre > code.sourceCode { white-space: pre; position: relative; }
      pre > code.sourceCode > span { line-height: 1.25; }
      pre > code.sourceCode > span:empty { height: 1.2em; }
      .sourceCode { overflow: visible; }
      code.sourceCode > span { color: inherit; text-decoration: inherit; }
      div.sourceCode { margin: 1em 0; }
      pre.sourceCode { margin: 0; }
      @media screen {
      div.sourceCode { overflow: auto; }
      }
      @media print {
      pre > code.sourceCode { white-space: pre-wrap; }
      pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
      }
      pre.numberSource code
        { counter-reset: source-line 0; }
      pre.numberSource code > span
        { position: relative; left: -4em; counter-increment: source-line; }
      pre.numberSource code > span > a:first-child::before
        { content: counter(source-line);
          position: relative; left: -1em; text-align: right; vertical-align: baseline;
          border: none; display: inline-block;
          -webkit-touch-callout: none; -webkit-user-select: none;
          -khtml-user-select: none; -moz-user-select: none;
          -ms-user-select: none; user-select: none;
          padding: 0 4px; width: 4em;
          background-color: #ffffff;
          color: #a0a0a0;
        }
      pre.numberSource { margin-left: 3em; border-left: 1px solid #a0a0a0;  padding-left: 4px; }
      div.sourceCode
        { color: #1f1c1b; background-color: #ffffff; }
      @media screen {
      pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
      }
      code span { color: #1f1c1b; } /* Normal */
      code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
      code span.an { color: #ca60ca; } /* Annotation */
      code span.at { color: #0057ae; } /* Attribute */
      code span.bn { color: #b08000; } /* BaseN */
      code span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
      code span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
      code span.ch { color: #924c9d; } /* Char */
      code span.cn { color: #aa5500; } /* Constant */
      code span.co { color: #898887; } /* Comment */
      code span.cv { color: #0095ff; } /* CommentVar */
      code span.do { color: #607880; } /* Documentation */
      code span.dt { color: #0057ae; } /* DataType */
      code span.dv { color: #b08000; } /* DecVal */
      code span.er { color: #bf0303; text-decoration: underline; } /* Error */
      code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
      code span.fl { color: #b08000; } /* Float */
      code span.fu { color: #644a9b; } /* Function */
      code span.im { color: #ff5500; } /* Import */
      code span.in { color: #b08000; } /* Information */
      code span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
      code span.op { color: #1f1c1b; } /* Operator */
      code span.ot { color: #006e28; } /* Other */
      code span.pp { color: #006e28; } /* Preprocessor */
      code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
      code span.sc { color: #3daee9; } /* SpecialChar */
      code span.ss { color: #ff5500; } /* SpecialString */
      code span.st { color: #bf0303; } /* String */
      code span.va { color: #0057ae; } /* Variable */
      code span.vs { color: #bf0303; } /* VerbatimString */
      code span.wa { color: #bf0303; } /* Warning */
    </style>
    
    
    <!-- tabsets -->
    <script>
      $(document).ready(function () {
	  window.buildTabsets("toc");
      });
      $(document).ready(function () {
	  $('.tabset-dropdown > .nav-tabs > li').click(function () {
	      $(this).parent().toggleClass('nav-tabs-open')
	  });
      });
    </script>

    <!-- code folding -->
    
    <!-- code download -->
    
    <!-- tabsets dropdown -->

    <style type="text/css">
      .tabset-dropdown > .nav-tabs {
	  display: inline-table;
	  max-height: 500px;
	  min-height: 44px;
	  overflow-y: auto;
	  background: white;
	  border: 1px solid #ddd;
	  border-radius: 4px;
      }
      
      .tabset-dropdown > .nav-tabs > li.active:before {
	  content: "";
	  font-family: 'Glyphicons Halflings';
	  display: inline-block;
	  padding: 10px;
	  border-right: 1px solid #ddd;
      }
      
      .tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
	  content: "&#xe258;";
	  border: none;
      }
      
      .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
	  content: "";
	  font-family: 'Glyphicons Halflings';
	  display: inline-block;
	  padding: 10px;
	  border-right: 1px solid #ddd;
      }
      
      .tabset-dropdown > .nav-tabs > li.active {
	  display: block;
      }

      .tabset-dropdown > .nav-tabs > li.active a {
  	  padding: 0 15px !important;
      }

      .tabset-dropdown > .nav-tabs > li > a,
      .tabset-dropdown > .nav-tabs > li > a:focus,
      .tabset-dropdown > .nav-tabs > li > a:hover {
	  border: none;
	  display: inline-block;
	  border-radius: 4px;
	  background-color: transparent;
      }
      
      .tabset-dropdown > .nav-tabs.nav-tabs-open > li {
	  display: block;
	  float: none;
      }
      
      .tabset-dropdown > .nav-tabs > li {
	  display: none;
	  margin-left: 0 !important;
      }
    </style>
    
</head>

<body class="preload">

   	
         <!-- readthedown start -->   
   <div id="content" data-toggle="wy-nav-shift">
     <nav id="nav-top" role="navigation" aria-label="top navigation">
       <a role="button" href="#" data-toggle="wy-nav-top"><span class="glyphicon glyphicon-menu-hamburger"></span></a>
     </nav>
         
   
        
      <h1 class="title">MH3510 Regression Analysis</h1>
      
         <!-- readthedown authors -->
   <div id="sidebar">
    <h2><a href="#content">MH3510 Regression Analysis</a></h2>
    <div id="toc">
      <ul>
      <li><a href="#setup-and-load-data"
      id="toc-setup-and-load-data">Setup and Load Data</a></li>
      <li><a href="#overview-of-the-data"
      id="toc-overview-of-the-data">Overview of the data</a></li>
      <li><a href="#graphic-display-of-the-observed-data"
      id="toc-graphic-display-of-the-observed-data">Graphic display of
      the observed data</a></li>
      <li><a href="#single-variable-analysis"
      id="toc-single-variable-analysis">Single Variable Analysis</a>
      <ul>
      <li><a href="#x1" id="toc-x1">X1</a></li>
      <li><a href="#x2" id="toc-x2">X2</a></li>
      <li><a href="#x3" id="toc-x3">X3</a></li>
      <li><a href="#x4" id="toc-x4">X4</a></li>
      </ul></li>
      <li><a href="#multiple-linear-regression"
      id="toc-multiple-linear-regression">Multiple Linear Regression</a>
      <ul>
      <li><a href="#adjusted-full-model"
      id="toc-adjusted-full-model">Adjusted Full Model</a></li>
      <li><a href="#adequacy-of-the-model"
      id="toc-adequacy-of-the-model">Adequacy of the model</a></li>
      </ul></li>
      <li><a href="#prediction" id="toc-prediction">Prediction</a>
      <ul>
      <li><a href="#data" id="toc-data">Data</a></li>
      <li><a href="#point-estimation" id="toc-point-estimation">Point
      Estimation</a></li>
      <li><a href="#interval-estimation"
      id="toc-interval-estimation">Interval Estimation</a></li>
      </ul></li>
      </ul>
    </div>
    <div id="postamble" data-toggle="wy-nav-shift" class="status">
                  <p class="author"><span class="glyphicon glyphicon-user"></span> Pu
Fanyi<a href="#fn1" class="footnote-ref"
id="fnref1"><sup>1</sup></a></p>
                        <p class="author"><span class="glyphicon glyphicon-user"></span> Zhang
Kaichen<a href="#fn2" class="footnote-ref"
id="fnref2"><sup>2</sup></a></p>
                        <p class="author"><span class="glyphicon glyphicon-user"></span> Shan
Yi<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a></p>
                        <p class="author"><span class="glyphicon glyphicon-user"></span> Fu
Yilin<a href="#fn4" class="footnote-ref"
id="fnref4"><sup>4</sup></a></p>
                        <p class="author"><span class="glyphicon glyphicon-user"></span> Mu
Yichen<a href="#fn5" class="footnote-ref"
id="fnref5"><sup>5</sup></a></p>
                        <p class="date"><span class="glyphicon glyphicon-calendar"></span> 2024-11-11</p>
          </div>
   </div>
     

   
      
   
<!-- Don't indent these lines or it will mess pre blocks indentation --> 
<div id="main">
<p><a href="https://pufanyi.github.io/MH3510-Project/">Main Page</a> /
<a
href="https://pufanyi.github.io/MH3510-Project/MH3510_Project.pdf">Report</a>
/ <a href="https://pufanyi.github.io/MH3510-Project/DataAnalysis">Code
(html)</a> / <a
href="https://pufanyi.github.io/MH3510-Project/DataAnalysis.pdf">Code
(pdf)</a> / <a href="https://github.com/pufanyi/MH3510-Project">Github
Repo</a></p>
<div id="setup-and-load-data" class="section level1">
<h1>Setup and Load Data</h1>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a><span class="fu">library</span>(latex2exp)</span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb1-7"><a href="#cb1-7" tabindex="-1"></a><span class="fu">library</span>(ggside)</span>
<span id="cb1-8"><a href="#cb1-8" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer)</span>
<span id="cb1-9"><a href="#cb1-9" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" tabindex="-1"></a>draw <span class="ot">&lt;-</span> <span class="cf">function</span>(drawing_function, file_path, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">8</span>) {</span>
<span id="cb1-12"><a href="#cb1-12" tabindex="-1"></a>  <span class="co"># Check if the directory exists</span></span>
<span id="cb1-13"><a href="#cb1-13" tabindex="-1"></a>  dir_path <span class="ot">&lt;-</span> <span class="fu">dirname</span>(file_path)</span>
<span id="cb1-14"><a href="#cb1-14" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">dir.exists</span>(dir_path)) {</span>
<span id="cb1-15"><a href="#cb1-15" tabindex="-1"></a>    <span class="fu">stop</span>(<span class="st">&quot;Directory does not exist: &quot;</span>, dir_path)</span>
<span id="cb1-16"><a href="#cb1-16" tabindex="-1"></a>  }</span>
<span id="cb1-17"><a href="#cb1-17" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" tabindex="-1"></a>  <span class="co"># Try to create the PDF</span></span>
<span id="cb1-19"><a href="#cb1-19" tabindex="-1"></a>  <span class="fu">tryCatch</span>(</span>
<span id="cb1-20"><a href="#cb1-20" tabindex="-1"></a>    {</span>
<span id="cb1-21"><a href="#cb1-21" tabindex="-1"></a>      <span class="fu">pdf</span>(file_path, <span class="at">width =</span> width, <span class="at">height =</span> height)</span>
<span id="cb1-22"><a href="#cb1-22" tabindex="-1"></a>      <span class="fu">drawing_function</span>()</span>
<span id="cb1-23"><a href="#cb1-23" tabindex="-1"></a>      <span class="fu">dev.off</span>()</span>
<span id="cb1-24"><a href="#cb1-24" tabindex="-1"></a>    },</span>
<span id="cb1-25"><a href="#cb1-25" tabindex="-1"></a>    <span class="at">error =</span> <span class="cf">function</span>(e) {</span>
<span id="cb1-26"><a href="#cb1-26" tabindex="-1"></a>      <span class="fu">message</span>(<span class="st">&quot;Error creating PDF: &quot;</span>, e<span class="sc">$</span>message)</span>
<span id="cb1-27"><a href="#cb1-27" tabindex="-1"></a>    }</span>
<span id="cb1-28"><a href="#cb1-28" tabindex="-1"></a>  )</span>
<span id="cb1-29"><a href="#cb1-29" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" tabindex="-1"></a>  <span class="co"># Display the plot</span></span>
<span id="cb1-31"><a href="#cb1-31" tabindex="-1"></a>  <span class="fu">drawing_function</span>()</span>
<span id="cb1-32"><a href="#cb1-32" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a>columns <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Y&quot;</span>, <span class="st">&quot;X1&quot;</span>, <span class="st">&quot;X2&quot;</span>, <span class="st">&quot;X3&quot;</span>, <span class="st">&quot;X4&quot;</span>, <span class="st">&quot;X5&quot;</span>, <span class="st">&quot;X6&quot;</span>, <span class="st">&quot;X7&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a>file <span class="ot">&lt;-</span> <span class="st">&quot;../assets/aadt.txt&quot;</span></span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a>data_raw <span class="ot">&lt;-</span> <span class="fu">read.table</span>(file, <span class="at">col.names =</span> columns)</span>
<span id="cb3-3"><a href="#cb3-3" tabindex="-1"></a>data_ori <span class="ot">&lt;-</span> data_raw[, <span class="fu">c</span>(<span class="st">&quot;Y&quot;</span>, <span class="st">&quot;X1&quot;</span>, <span class="st">&quot;X2&quot;</span>, <span class="st">&quot;X3&quot;</span>, <span class="st">&quot;X4&quot;</span>)]</span>
<span id="cb3-4"><a href="#cb3-4" tabindex="-1"></a>data <span class="ot">&lt;-</span> data_ori</span>
<span id="cb3-5"><a href="#cb3-5" tabindex="-1"></a><span class="fu">head</span>(data)</span></code></pre></div>
<pre><code>##      Y    X1 X2 X3 X4
## 1 1616 13404  2 52  2
## 2 1329 52314  2 60  2
## 3 3933 30982  2 57  2
## 4 3786 25207  2 64  2
## 5  465 20594  2 40  2
## 6  794 11507  2 44  2</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a>image_folder <span class="ot">&lt;-</span> <span class="st">&quot;../assets/images/&quot;</span></span></code></pre></div>
</div>
<div id="overview-of-the-data" class="section level1">
<h1>Overview of the data</h1>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a>overview_image_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(image_folder, <span class="st">&quot;overview&quot;</span>)</span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a><span class="fu">dir.create</span>(overview_image_path, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="co"># Create separate plots for each variable</span></span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a>plot_Y <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Y)) <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb7-4"><a href="#cb7-4" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;lightblue&quot;</span>,</span>
<span id="cb7-5"><a href="#cb7-5" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">bins =</span> <span class="dv">30</span>, <span class="at">alpha =</span> <span class="fl">0.6</span></span>
<span id="cb7-6"><a href="#cb7-6" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-7"><a href="#cb7-7" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb7-8"><a href="#cb7-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribution of Y&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-9"><a href="#cb7-9" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb7-10"><a href="#cb7-10" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" tabindex="-1"></a>plot_X1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> X1)) <span class="sc">+</span></span>
<span id="cb7-12"><a href="#cb7-12" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb7-13"><a href="#cb7-13" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;lightblue&quot;</span>,</span>
<span id="cb7-14"><a href="#cb7-14" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">bins =</span> <span class="dv">30</span>, <span class="at">alpha =</span> <span class="fl">0.6</span></span>
<span id="cb7-15"><a href="#cb7-15" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-16"><a href="#cb7-16" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb7-17"><a href="#cb7-17" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribution of X1&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-18"><a href="#cb7-18" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb7-19"><a href="#cb7-19" tabindex="-1"></a></span>
<span id="cb7-20"><a href="#cb7-20" tabindex="-1"></a>plot_X2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> X2)) <span class="sc">+</span></span>
<span id="cb7-21"><a href="#cb7-21" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb7-22"><a href="#cb7-22" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;lightblue&quot;</span>,</span>
<span id="cb7-23"><a href="#cb7-23" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">bins =</span> <span class="dv">30</span>, <span class="at">alpha =</span> <span class="fl">0.6</span></span>
<span id="cb7-24"><a href="#cb7-24" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-25"><a href="#cb7-25" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb7-26"><a href="#cb7-26" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribution of X2&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-27"><a href="#cb7-27" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb7-28"><a href="#cb7-28" tabindex="-1"></a></span>
<span id="cb7-29"><a href="#cb7-29" tabindex="-1"></a>plot_X3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> X3)) <span class="sc">+</span></span>
<span id="cb7-30"><a href="#cb7-30" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb7-31"><a href="#cb7-31" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;lightblue&quot;</span>,</span>
<span id="cb7-32"><a href="#cb7-32" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">bins =</span> <span class="dv">30</span>, <span class="at">alpha =</span> <span class="fl">0.6</span></span>
<span id="cb7-33"><a href="#cb7-33" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-34"><a href="#cb7-34" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb7-35"><a href="#cb7-35" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribution of X3&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-36"><a href="#cb7-36" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb7-37"><a href="#cb7-37" tabindex="-1"></a></span>
<span id="cb7-38"><a href="#cb7-38" tabindex="-1"></a><span class="co"># Arrange histograms in 2x2 grid</span></span>
<span id="cb7-39"><a href="#cb7-39" tabindex="-1"></a>histogram_grid <span class="ot">&lt;-</span> <span class="fu">arrangeGrob</span>(</span>
<span id="cb7-40"><a href="#cb7-40" tabindex="-1"></a>  plot_Y, plot_X1, plot_X2, plot_X3,</span>
<span id="cb7-41"><a href="#cb7-41" tabindex="-1"></a>  <span class="at">ncol =</span> <span class="dv">2</span>,</span>
<span id="cb7-42"><a href="#cb7-42" tabindex="-1"></a>  <span class="at">nrow =</span> <span class="dv">2</span></span>
<span id="cb7-43"><a href="#cb7-43" tabindex="-1"></a>)</span></code></pre></div>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="co"># Create pie chart for X4</span></span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a>x4_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(data<span class="sc">$</span>X4)</span>
<span id="cb8-3"><a href="#cb8-3" tabindex="-1"></a>plot_X4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">data.frame</span>(x4_counts), <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> Freq, <span class="at">fill =</span> Var1)) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">width =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" tabindex="-1"></a>  <span class="fu">coord_polar</span>(<span class="st">&quot;y&quot;</span>, <span class="at">start =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb8-7"><a href="#cb8-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribution of X4&quot;</span>,</span>
<span id="cb8-8"><a href="#cb8-8" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;Category&quot;</span></span>
<span id="cb8-9"><a href="#cb8-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb8-10"><a href="#cb8-10" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(</span>
<span id="cb8-11"><a href="#cb8-11" tabindex="-1"></a>    <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;#FF9999&quot;</span>, <span class="st">&quot;#66B2FF&quot;</span>),</span>
<span id="cb8-12"><a href="#cb8-12" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;yes&quot;</span>, <span class="st">&quot;no&quot;</span>)</span>
<span id="cb8-13"><a href="#cb8-13" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb8-14"><a href="#cb8-14" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb8-15"><a href="#cb8-15" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb8-16"><a href="#cb8-16" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb8-17"><a href="#cb8-17" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>,</span>
<span id="cb8-18"><a href="#cb8-18" tabindex="-1"></a>    <span class="at">legend.title =</span> <span class="fu">element_text</span>(),</span>
<span id="cb8-19"><a href="#cb8-19" tabindex="-1"></a>    <span class="at">panel.grid =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb8-20"><a href="#cb8-20" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb8-21"><a href="#cb8-21" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb8-22"><a href="#cb8-22" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb8-23"><a href="#cb8-23" tabindex="-1"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb8-24"><a href="#cb8-24" tabindex="-1"></a>    <span class="fu">aes</span>(</span>
<span id="cb8-25"><a href="#cb8-25" tabindex="-1"></a>      <span class="at">label =</span> <span class="fu">paste0</span>(<span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> Freq <span class="sc">/</span> <span class="fu">sum</span>(Freq), <span class="dv">1</span>), <span class="st">&quot;%&quot;</span>)</span>
<span id="cb8-26"><a href="#cb8-26" tabindex="-1"></a>    ),</span>
<span id="cb8-27"><a href="#cb8-27" tabindex="-1"></a>    <span class="at">position =</span> <span class="fu">position_stack</span>(<span class="at">vjust =</span> <span class="fl">0.5</span>)</span>
<span id="cb8-28"><a href="#cb8-28" tabindex="-1"></a>  )</span>
<span id="cb8-29"><a href="#cb8-29" tabindex="-1"></a></span>
<span id="cb8-30"><a href="#cb8-30" tabindex="-1"></a><span class="co"># Combine histogram grid and pie chart vertically</span></span>
<span id="cb8-31"><a href="#cb8-31" tabindex="-1"></a>combined_plot <span class="ot">&lt;-</span> <span class="fu">grid.arrange</span>(</span>
<span id="cb8-32"><a href="#cb8-32" tabindex="-1"></a>  histogram_grid,</span>
<span id="cb8-33"><a href="#cb8-33" tabindex="-1"></a>  plot_X4,</span>
<span id="cb8-34"><a href="#cb8-34" tabindex="-1"></a>  <span class="at">ncol =</span> <span class="dv">2</span>,</span>
<span id="cb8-35"><a href="#cb8-35" tabindex="-1"></a>  <span class="at">widths =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb8-36"><a href="#cb8-36" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="DataAnalysis_files/figure-html/unnamed-chunk-6-1.png" width="960" /></p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a>combined_plot_image_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(</span>
<span id="cb9-2"><a href="#cb9-2" tabindex="-1"></a>  overview_image_path,</span>
<span id="cb9-3"><a href="#cb9-3" tabindex="-1"></a>  <span class="st">&quot;combined_histograms.pdf&quot;</span></span>
<span id="cb9-4"><a href="#cb9-4" tabindex="-1"></a>)</span>
<span id="cb9-5"><a href="#cb9-5" tabindex="-1"></a><span class="fu">ggsave</span>(combined_plot_image_path, combined_plot, <span class="at">width =</span> <span class="dv">10</span>, <span class="at">height =</span> <span class="dv">5</span>)</span></code></pre></div>
</div>
<div id="graphic-display-of-the-observed-data" class="section level1">
<h1>Graphic display of the observed data</h1>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a><span class="fu">pdf</span>(<span class="fu">file.path</span>(image_folder, <span class="st">&quot;overview.pdf&quot;</span>), <span class="at">width =</span> <span class="dv">10</span>, <span class="at">height =</span> <span class="dv">10</span>)</span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a><span class="fu">ggpairs</span>(data,</span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a>  <span class="at">upper =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">&quot;points&quot;</span>,</span>
<span id="cb10-4"><a href="#cb10-4" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb10-5"><a href="#cb10-5" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">2</span></span>
<span id="cb10-6"><a href="#cb10-6" tabindex="-1"></a>  )),</span>
<span id="cb10-7"><a href="#cb10-7" tabindex="-1"></a>  <span class="at">lower =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">&quot;points&quot;</span>,</span>
<span id="cb10-8"><a href="#cb10-8" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb10-9"><a href="#cb10-9" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">2</span></span>
<span id="cb10-10"><a href="#cb10-10" tabindex="-1"></a>  )),</span>
<span id="cb10-11"><a href="#cb10-11" tabindex="-1"></a>  <span class="at">diag =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">&quot;densityDiag&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;lightblue&quot;</span>))</span>
<span id="cb10-12"><a href="#cb10-12" tabindex="-1"></a>)</span>
<span id="cb10-13"><a href="#cb10-13" tabindex="-1"></a><span class="fu">dev.off</span>()</span></code></pre></div>
<pre><code>## png 
##   2</code></pre>
<p>We let <span class="math inline">\(y&#39; = \log y\)</span> to fix
the skewness of the data.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a>y_prime <span class="ot">&lt;-</span> <span class="fu">log</span>(data<span class="sc">$</span>Y)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>y_prime_fig <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">data.frame</span>(y_prime), <span class="fu">aes</span>(<span class="at">x =</span> y_prime)) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb12-4"><a href="#cb12-4" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;lightblue&quot;</span>,</span>
<span id="cb12-5"><a href="#cb12-5" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">bins =</span> <span class="dv">30</span>, <span class="at">alpha =</span> <span class="fl">0.6</span></span>
<span id="cb12-6"><a href="#cb12-6" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-7"><a href="#cb12-7" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb12-8"><a href="#cb12-8" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb12-9"><a href="#cb12-9" tabindex="-1"></a>    <span class="at">title =</span> <span class="fu">TeX</span>(<span class="st">&quot;Distribution of $y&#39; = </span><span class="sc">\\</span><span class="st">log^2y$&quot;</span>),</span>
<span id="cb12-10"><a href="#cb12-10" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">TeX</span>(<span class="st">&quot;$y&#39; = </span><span class="sc">\\</span><span class="st">log^2y$&quot;</span>)</span>
<span id="cb12-11"><a href="#cb12-11" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-12"><a href="#cb12-12" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb12-13"><a href="#cb12-13" tabindex="-1"></a>y_prime_fig</span></code></pre></div>
<p><img src="DataAnalysis_files/figure-html/unnamed-chunk-8-1.png" width="768" /></p>
<p>Finally, we replace the original <span
class="math inline">\(y\)</span> with <span
class="math inline">\(y&#39;\)</span>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a>data<span class="sc">$</span>Y <span class="ot">&lt;-</span> y_prime</span></code></pre></div>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a>x1_prime <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(data<span class="sc">$</span>X1)</span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a>x1_prime_fig <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">data.frame</span>(x1_prime), <span class="fu">aes</span>(<span class="at">x =</span> x1_prime)) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb14-4"><a href="#cb14-4" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;lightblue&quot;</span>,</span>
<span id="cb14-5"><a href="#cb14-5" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">bins =</span> <span class="dv">30</span>, <span class="at">alpha =</span> <span class="fl">0.6</span></span>
<span id="cb14-6"><a href="#cb14-6" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb14-9"><a href="#cb14-9" tabindex="-1"></a>    <span class="at">title =</span> <span class="fu">TeX</span>(<span class="st">&quot;Distribution of $x_1&#39; = </span><span class="sc">\\</span><span class="st">sqrt{x_1}$&quot;</span>),</span>
<span id="cb14-10"><a href="#cb14-10" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">TeX</span>(<span class="st">&quot;$x_1&#39;=</span><span class="sc">\\</span><span class="st">sqrt{x_1}$&quot;</span>)</span>
<span id="cb14-11"><a href="#cb14-11" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb14-12"><a href="#cb14-12" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb14-13"><a href="#cb14-13" tabindex="-1"></a>x1_prime_fig</span></code></pre></div>
<p><img src="DataAnalysis_files/figure-html/unnamed-chunk-10-1.png" width="768" /></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a>data<span class="sc">$</span>X1 <span class="ot">&lt;-</span> x1_prime</span></code></pre></div>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a><span class="co"># merge graphs</span></span>
<span id="cb16-2"><a href="#cb16-2" tabindex="-1"></a>merged_graphs <span class="ot">&lt;-</span> <span class="fu">grid.arrange</span>(</span>
<span id="cb16-3"><a href="#cb16-3" tabindex="-1"></a>  y_prime_fig,</span>
<span id="cb16-4"><a href="#cb16-4" tabindex="-1"></a>  x1_prime_fig,</span>
<span id="cb16-5"><a href="#cb16-5" tabindex="-1"></a>  <span class="at">ncol =</span> <span class="dv">2</span>,</span>
<span id="cb16-6"><a href="#cb16-6" tabindex="-1"></a>  <span class="at">widths =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb16-7"><a href="#cb16-7" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="DataAnalysis_files/figure-html/unnamed-chunk-12-1.png" width="768" /></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="fu">file.path</span>(overview_image_path, <span class="st">&quot;transformed_variables.pdf&quot;</span>),</span>
<span id="cb17-2"><a href="#cb17-2" tabindex="-1"></a>  merged_graphs,</span>
<span id="cb17-3"><a href="#cb17-3" tabindex="-1"></a>  <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">3</span></span>
<span id="cb17-4"><a href="#cb17-4" tabindex="-1"></a>)</span></code></pre></div>
<p>The distribution of <span class="math inline">\(y&#39;\)</span> and
<span class="math inline">\(x_1&#39;\)</span>, it can be seen that the
distributions of <span class="math inline">\(y&#39;\)</span> and <span
class="math inline">\(x_1&#39;\)</span> are relatively uniform compared
with the original <span class="math inline">\(y\)</span> and <span
class="math inline">\(x_1\)</span>.</p>
<p>Although <span class="math inline">\(x_2\)</span> and <span
class="math inline">\(x_3\)</span> also have some skewness, considering
that they are integers with a small range in the dataset, applying a
transformation may not be useful. We have decided not to transform them
for now.</p>
</div>
<div id="single-variable-analysis" class="section level1">
<h1>Single Variable Analysis</h1>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a>slr_output_folder <span class="ot">&lt;-</span> <span class="fu">file.path</span>(image_folder, <span class="st">&quot;slr&quot;</span>)</span>
<span id="cb18-2"><a href="#cb18-2" tabindex="-1"></a><span class="fu">dir.create</span>(slr_output_folder, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<div id="x1" class="section level2">
<h2>X1</h2>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" tabindex="-1"></a>X1_output_folder <span class="ot">&lt;-</span> <span class="fu">file.path</span>(slr_output_folder, <span class="st">&quot;X1&quot;</span>)</span>
<span id="cb19-2"><a href="#cb19-2" tabindex="-1"></a><span class="fu">dir.create</span>(X1_output_folder, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="co"># scatter plot</span></span>
<span id="cb20-2"><a href="#cb20-2" tabindex="-1"></a>scatter_plot_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(X1_output_folder, <span class="st">&quot;scatter_plot.pdf&quot;</span>)</span>
<span id="cb20-3"><a href="#cb20-3" tabindex="-1"></a>scatter_plot_X1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> x1_prime, <span class="at">y =</span> y_prime)) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb20-7"><a href="#cb20-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="fu">TeX</span>(<span class="st">&quot;Scatter Plot of $y&#39;$ vs. $x_1&#39;$&quot;</span>),</span>
<span id="cb20-8"><a href="#cb20-8" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">TeX</span>(<span class="st">&quot;$x_1&#39;=</span><span class="sc">\\</span><span class="st">sqrt{x_1}$&quot;</span>), <span class="at">y =</span> <span class="fu">TeX</span>(<span class="st">&quot;$y&#39;=</span><span class="sc">\\</span><span class="st">log^2 y$&quot;</span>)</span>
<span id="cb20-9"><a href="#cb20-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb20-10"><a href="#cb20-10" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb20-11"><a href="#cb20-11" tabindex="-1"></a><span class="fu">ggsave</span>(scatter_plot_path, scatter_plot_X1, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">6</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" tabindex="-1"></a>scatter_plot_X1</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="DataAnalysis_files/figure-html/unnamed-chunk-15-1.png" width="768" /></p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a>slr_X1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y_prime <span class="sc">~</span> x1_prime, <span class="at">data =</span> data)</span>
<span id="cb24-2"><a href="#cb24-2" tabindex="-1"></a><span class="fu">summary</span>(slr_X1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y_prime ~ x1_prime, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -71.497 -15.752  -2.273  15.791  40.708 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 53.487764   3.232405   16.55   &lt;2e-16 ***
## x1_prime     0.063839   0.006298   10.14   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 20.57 on 119 degrees of freedom
## Multiple R-squared:  0.4634, Adjusted R-squared:  0.4588 
## F-statistic: 102.7 on 1 and 119 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We draw the residuals plot and QQ-plot to provide further insights
into the model’s adequacy.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a><span class="co"># Create the main plot with the residuals</span></span>
<span id="cb26-2"><a href="#cb26-2" tabindex="-1"></a>plot_resid_X1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb26-3"><a href="#cb26-3" tabindex="-1"></a>  <span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">fitted =</span> <span class="fu">fitted</span>(slr_X1), <span class="at">residuals =</span> <span class="fu">resid</span>(slr_X1)),</span>
<span id="cb26-4"><a href="#cb26-4" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> fitted, <span class="at">y =</span> residuals)</span>
<span id="cb26-5"><a href="#cb26-5" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb26-6"><a href="#cb26-6" tabindex="-1"></a>  <span class="co"># Add points on top</span></span>
<span id="cb26-7"><a href="#cb26-7" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;#1f78b4&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb26-8"><a href="#cb26-8" tabindex="-1"></a>  <span class="co"># Original elements</span></span>
<span id="cb26-9"><a href="#cb26-9" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb26-10"><a href="#cb26-10" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Fitted values&quot;</span>,</span>
<span id="cb26-11"><a href="#cb26-11" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Residuals&quot;</span>,</span>
<span id="cb26-12"><a href="#cb26-12" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Residuals vs Fitted&quot;</span></span>
<span id="cb26-13"><a href="#cb26-13" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb26-14"><a href="#cb26-14" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb26-15"><a href="#cb26-15" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">&quot;C&quot;</span>) <span class="sc">+</span> <span class="co"># Changed to discrete scale</span></span>
<span id="cb26-16"><a href="#cb26-16" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb26-17"><a href="#cb26-17" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb26-18"><a href="#cb26-18" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb26-19"><a href="#cb26-19" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb26-20"><a href="#cb26-20" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>),</span>
<span id="cb26-21"><a href="#cb26-21" tabindex="-1"></a>  )</span>
<span id="cb26-22"><a href="#cb26-22" tabindex="-1"></a></span>
<span id="cb26-23"><a href="#cb26-23" tabindex="-1"></a>qqplot_X1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb26-24"><a href="#cb26-24" tabindex="-1"></a>  <span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">sample =</span> <span class="fu">resid</span>(slr_X1)),</span>
<span id="cb26-25"><a href="#cb26-25" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">sample =</span> sample)</span>
<span id="cb26-26"><a href="#cb26-26" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb26-27"><a href="#cb26-27" tabindex="-1"></a>  <span class="fu">stat_qq</span>(<span class="at">color =</span> <span class="st">&quot;#1f78b4&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb26-28"><a href="#cb26-28" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="at">color =</span> <span class="st">&quot;#e31a1c&quot;</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb26-29"><a href="#cb26-29" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb26-30"><a href="#cb26-30" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Theoretical Quantiles&quot;</span>,</span>
<span id="cb26-31"><a href="#cb26-31" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Sample Quantiles&quot;</span>,</span>
<span id="cb26-32"><a href="#cb26-32" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Normal Q-Q&quot;</span></span>
<span id="cb26-33"><a href="#cb26-33" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb26-34"><a href="#cb26-34" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb26-35"><a href="#cb26-35" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb26-36"><a href="#cb26-36" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb26-37"><a href="#cb26-37" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb26-38"><a href="#cb26-38" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb26-39"><a href="#cb26-39" tabindex="-1"></a>  )</span>
<span id="cb26-40"><a href="#cb26-40" tabindex="-1"></a></span>
<span id="cb26-41"><a href="#cb26-41" tabindex="-1"></a>x1_fig <span class="ot">&lt;-</span> <span class="fu">grid.arrange</span>(plot_resid_X1, qqplot_X1, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="DataAnalysis_files/figure-html/unnamed-chunk-17-1.png" width="960" /></p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="fu">file.path</span>(X1_output_folder, <span class="st">&quot;residuals_vs_fitted_qqplot.pdf&quot;</span>),</span>
<span id="cb27-2"><a href="#cb27-2" tabindex="-1"></a>  x1_fig,</span>
<span id="cb27-3"><a href="#cb27-3" tabindex="-1"></a>  <span class="at">width =</span> <span class="dv">10</span>, <span class="at">height =</span> <span class="dv">4</span></span>
<span id="cb27-4"><a href="#cb27-4" tabindex="-1"></a>)</span></code></pre></div>
<p>The residual plot in Figure 5 shows a generally even distribution of
residuals around zero, though there are some signs of non-constant
variance. This pattern might indicate that variability in traffic
increases with larger predicted values, potentially due to factors such
as urban infrastructure or public transport usage that could influence
traffic in larger counties.</p>
<p>The QQ-plot of residuals shows that the residuals mostly follow a
normal distribution, with minor deviations at the tails, suggesting that
while the model performs well overall, there might be outliers or
specific population segments where the prediction is less accurate.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" tabindex="-1"></a>aov <span class="ot">&lt;-</span> <span class="fu">anova</span>(slr_X1)</span>
<span id="cb28-2"><a href="#cb28-2" tabindex="-1"></a>aov</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: y_prime
##            Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## x1_prime    1  43471   43471  102.75 &lt; 2.2e-16 ***
## Residuals 119  50347     423                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Since the F value is in an F distribution, we conduct an F-test and
obtain a p-value of less than <span class="math inline">\(2 \times
10^{-16}\)</span>. The p-value is small enough for us to reject <span
class="math inline">\(H_0\)</span> and conclude that the population
actually has an influence on AADT.</p>
<p>The <span class="math inline">\(R^2\)</span> statistic is calculated
as approximately <span class="math inline">\(0.4634\)</span>. This means
that while there is some relationship between population and AADT, there
are other factors that determine the AADT.</p>
</div>
<div id="x2" class="section level2">
<h2>X2</h2>
<p>The x-axis representing the number of lanes. The y-axis representing
the AADT data after transformation.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a>X2_output_folder <span class="ot">&lt;-</span> <span class="fu">file.path</span>(slr_output_folder, <span class="st">&quot;X2&quot;</span>)</span>
<span id="cb30-2"><a href="#cb30-2" tabindex="-1"></a><span class="fu">dir.create</span>(X2_output_folder, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>In this plot, we also include a trendline to indicate the general
pattern in the data. A positive slope in the trendline has been ovserved
in the plot, which means that as the number of lanes increases, AADT
tends to increase as well. This aligns with common sense: adding lanes
generally allows a road to support more vehicles, which increases its
traffic capacity.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" tabindex="-1"></a><span class="co"># scatter plot</span></span>
<span id="cb31-2"><a href="#cb31-2" tabindex="-1"></a>scatter_plot_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(X2_output_folder, <span class="st">&quot;scatter_plot.pdf&quot;</span>)</span>
<span id="cb31-3"><a href="#cb31-3" tabindex="-1"></a>scatter_plot_X2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> X2, <span class="at">y =</span> Y)) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Scatter Plot of Y vs. X2&quot;</span>, <span class="at">x =</span> <span class="st">&quot;X2&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Y&quot;</span>) <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb31-8"><a href="#cb31-8" tabindex="-1"></a><span class="fu">ggsave</span>(scatter_plot_path, scatter_plot_X2, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">6</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" tabindex="-1"></a>scatter_plot_X2</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="DataAnalysis_files/figure-html/unnamed-chunk-20-1.png" width="768" /></p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" tabindex="-1"></a>slr_X2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X2, <span class="at">data =</span> data)</span>
<span id="cb35-2"><a href="#cb35-2" tabindex="-1"></a><span class="fu">summary</span>(slr_X2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y ~ X2, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -32.614 -10.185   0.024   9.303  34.108 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   25.304      3.754    6.74    6e-10 ***
## X2            17.718      1.118   15.85   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 15.92 on 119 degrees of freedom
## Multiple R-squared:  0.6786, Adjusted R-squared:  0.6759 
## F-statistic: 251.3 on 1 and 119 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Intercept</strong><br />
When the number of lanes is zero, the model predicts <span
class="math inline">\(y&#39;\)</span> of approximately 25.3. While this
might not be meaningful practically (since we rarely see roads with zero
lanes), it serves as a baseline.</p>
<p><strong>Slope for</strong> <span
class="math inline">\(x_2\)</span><br />
For each additional lane, the model predicts an increase of about 17.7
in <span class="math inline">\(y&#39;\)</span>. This means adding lanes
has a significant positive effect on traffic capacity.</p>
<p><strong>Significance</strong><br />
The very low <em>p</em>-value (<span class="math inline">\(&lt; 2 \times
10^{-16}\)</span>) for the number of lanes indicates that this
relationship is statistically significant, implying that the number of
lanes is an important factor in determining AADT.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" tabindex="-1"></a><span class="co"># Create the main plot with the residuals</span></span>
<span id="cb37-2"><a href="#cb37-2" tabindex="-1"></a>plot_resid_X2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb37-3"><a href="#cb37-3" tabindex="-1"></a>  <span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">fitted =</span> <span class="fu">fitted</span>(slr_X2), <span class="at">residuals =</span> <span class="fu">resid</span>(slr_X2)),</span>
<span id="cb37-4"><a href="#cb37-4" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> fitted, <span class="at">y =</span> residuals)</span>
<span id="cb37-5"><a href="#cb37-5" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb37-6"><a href="#cb37-6" tabindex="-1"></a>  <span class="co"># Add points on top</span></span>
<span id="cb37-7"><a href="#cb37-7" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;#1f78b4&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb37-8"><a href="#cb37-8" tabindex="-1"></a>  <span class="co"># Original elements</span></span>
<span id="cb37-9"><a href="#cb37-9" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb37-10"><a href="#cb37-10" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Fitted values&quot;</span>,</span>
<span id="cb37-11"><a href="#cb37-11" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Residuals&quot;</span>,</span>
<span id="cb37-12"><a href="#cb37-12" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Residuals vs Fitted&quot;</span></span>
<span id="cb37-13"><a href="#cb37-13" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb37-14"><a href="#cb37-14" tabindex="-1"></a>  <span class="co"># geom_smooth(method = &quot;loess&quot;, color = &quot;red&quot;, size = 1) +</span></span>
<span id="cb37-15"><a href="#cb37-15" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb37-16"><a href="#cb37-16" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">&quot;C&quot;</span>) <span class="sc">+</span> <span class="co"># Changed to discrete scale</span></span>
<span id="cb37-17"><a href="#cb37-17" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb37-18"><a href="#cb37-18" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb37-19"><a href="#cb37-19" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb37-20"><a href="#cb37-20" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb37-21"><a href="#cb37-21" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>),</span>
<span id="cb37-22"><a href="#cb37-22" tabindex="-1"></a>  )</span>
<span id="cb37-23"><a href="#cb37-23" tabindex="-1"></a></span>
<span id="cb37-24"><a href="#cb37-24" tabindex="-1"></a>qqplot_X2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb37-25"><a href="#cb37-25" tabindex="-1"></a>  <span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">sample =</span> <span class="fu">resid</span>(slr_X2)),</span>
<span id="cb37-26"><a href="#cb37-26" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">sample =</span> sample)</span>
<span id="cb37-27"><a href="#cb37-27" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb37-28"><a href="#cb37-28" tabindex="-1"></a>  <span class="fu">stat_qq</span>(<span class="at">color =</span> <span class="st">&quot;#1f78b4&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb37-29"><a href="#cb37-29" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="at">color =</span> <span class="st">&quot;#e31a1c&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb37-30"><a href="#cb37-30" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb37-31"><a href="#cb37-31" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Theoretical Quantiles&quot;</span>,</span>
<span id="cb37-32"><a href="#cb37-32" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Sample Quantiles&quot;</span>,</span>
<span id="cb37-33"><a href="#cb37-33" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Normal Q-Q&quot;</span></span>
<span id="cb37-34"><a href="#cb37-34" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb37-35"><a href="#cb37-35" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb37-36"><a href="#cb37-36" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb37-37"><a href="#cb37-37" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb37-38"><a href="#cb37-38" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb37-39"><a href="#cb37-39" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb37-40"><a href="#cb37-40" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## ℹ Please use `linewidth` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" tabindex="-1"></a>x2_fig <span class="ot">&lt;-</span> <span class="fu">grid.arrange</span>(plot_resid_X2, qqplot_X2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="DataAnalysis_files/figure-html/unnamed-chunk-22-1.png" width="960" /></p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="fu">file.path</span>(X2_output_folder, <span class="st">&quot;residuals_vs_fitted_qqplot.pdf&quot;</span>),</span>
<span id="cb40-2"><a href="#cb40-2" tabindex="-1"></a>  x2_fig,</span>
<span id="cb40-3"><a href="#cb40-3" tabindex="-1"></a>  <span class="at">width =</span> <span class="dv">10</span>, <span class="at">height =</span> <span class="dv">4</span></span>
<span id="cb40-4"><a href="#cb40-4" tabindex="-1"></a>)</span></code></pre></div>
<p>Residuals vs Fitted Plot The graph above examines how well the linear
model predicts AADT based on the number of lanes. If the residuals (the
differences between actual and predicted AADT) are scattered randomly
around the zero line, it indicates that the number of lanes effectively
explains variations in AADT. In practical terms, this would mean that
road sections with different lane counts generally show predictable
changes in traffic volume, and our model captures this relationship
well. However, if a pattern appears in the residuals, such as a
consistent underestimation or overestimation of AADT for certain lane
counts, it might suggest that factors beyond lane count (e.g., location,
road type) are also influencing traffic volume, indicating that our
model may need additional variables to improve accuracy.</p>
<p>Normal QQ-Ploy it assesses whether the residuals are normally
distributed, which is an assumption for linear regression. A normal
distribution of residuals suggests that the relationship between lane
count and AADT is generally well-captured by the linear model. If the
points fall along a straight line in the Q-Q plot, it indicates that the
model’s errors are random and unbiased, meaning our predictions are
reasonably reliable across different lane counts. However, significant
deviations from this line might indicate that the relationship between
lane count and AADT isn’t fully linear or that other factors are
affecting traffic volume in ways the model doesn’t capture, possibly
warranting a more complex or adjusted model.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" tabindex="-1"></a>aov <span class="ot">&lt;-</span> <span class="fu">anova</span>(slr_X2)</span>
<span id="cb41-2"><a href="#cb41-2" tabindex="-1"></a>aov</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Y
##            Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## X2          1  63665   63665  251.25 &lt; 2.2e-16 ***
## Residuals 119  30153     253                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>According to Equation 5, we can build <span
class="math inline">\(H_0: \beta_1 = 0\)</span> and <span
class="math inline">\(H_1: \beta_1 \neq 0\)</span>. We conduct an F-test
by calculating the <em>p</em> value.</p>
<p>The <em>p</em> value is small enough for us to reject <span
class="math inline">\(H_0\)</span> and conclude that the population
actually has an influence on AADT.</p>
<p>The <span class="math inline">\(R^2\)</span> statistic is calculated
as approximately 0.4634.</p>
<p>This means that while there is some relationship between population
and AADT, there are other factors that determine AADT.</p>
<p>Summary</p>
<p>This analysis shows that the number of lanes has a strong, positive
effect on AADT. This makes intuitive sense, as wider roads with more
lanes are better suited to handle larger volumes of traffic. The linear
model and diagnostic plots suggest that the relationship is well
captured by our model, with residuals generally behaving as expected. In
summary, as we add more lanes to a road, we can expect an increase in
daily traffic capacity, which matches our common-sense understanding of
road infrastructure and traffic flow.</p>
</div>
<div id="x3" class="section level2">
<h2>X3</h2>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" tabindex="-1"></a>X3_output_folder <span class="ot">&lt;-</span> <span class="fu">file.path</span>(slr_output_folder, <span class="st">&quot;X3&quot;</span>)</span>
<span id="cb43-2"><a href="#cb43-2" tabindex="-1"></a><span class="fu">dir.create</span>(X3_output_folder, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" tabindex="-1"></a><span class="co"># scatter plot</span></span>
<span id="cb44-2"><a href="#cb44-2" tabindex="-1"></a>scatter_plot_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(X3_output_folder, <span class="st">&quot;scatter_plot.pdf&quot;</span>)</span>
<span id="cb44-3"><a href="#cb44-3" tabindex="-1"></a>scatter_plot_X3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> X3, <span class="at">y =</span> Y)) <span class="sc">+</span></span>
<span id="cb44-4"><a href="#cb44-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb44-5"><a href="#cb44-5" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb44-6"><a href="#cb44-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Scatter Plot of Y vs. X3&quot;</span>, <span class="at">x =</span> <span class="st">&quot;X3&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Y&quot;</span>) <span class="sc">+</span></span>
<span id="cb44-7"><a href="#cb44-7" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb44-8"><a href="#cb44-8" tabindex="-1"></a><span class="fu">ggsave</span>(scatter_plot_path, scatter_plot_X3, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">6</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" tabindex="-1"></a>scatter_plot_X3</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="DataAnalysis_files/figure-html/unnamed-chunk-25-1.png" width="768" /></p>
<p>The scatter plot shows the relationship between Annual Average Daily
Traffic (AADT) and the width of road sections (in feet). Each point
represents a specific road section, with: The x-axis represents the
width of the road section in feet x3. The y-axis represents the
AADT.</p>
<p>In this plot, a trendline has been added to indicate the general
pattern in the data. Although the trendline suggests a positive slope,
indicating that as the road width increases, AADT tends to increase,
this relationship is not statistically significant, as shown by the
linear model.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" tabindex="-1"></a>slr_X3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X3, <span class="at">data =</span> data)</span>
<span id="cb48-2"><a href="#cb48-2" tabindex="-1"></a><span class="fu">summary</span>(slr_X3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y ~ X3, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -49.532 -23.161   0.716  20.602  61.334 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  71.4902     7.3225   9.763   &lt;2e-16 ***
## X3            0.2803     0.2207   1.270    0.207    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 27.89 on 119 degrees of freedom
## Multiple R-squared:  0.01337,    Adjusted R-squared:  0.00508 
## F-statistic: 1.613 on 1 and 119 DF,  p-value: 0.2066</code></pre>
<p>Intercept: 71.49, which suggests that at a hypothetical width of
zero, the model would predict an AADT of approximately 71.5, though this
does not have practical meaning.</p>
<p>Slope for x3: 0.28, indicating a predicted increase in AADT of
approximately 0.28 for each additional foot in road width. However, this
effect is not statistically significant (p-value = 0.207), suggesting
that road width does not significantly impact AADT in this model.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" tabindex="-1"></a>aov <span class="ot">&lt;-</span> <span class="fu">anova</span>(slr_X3)</span>
<span id="cb50-2"><a href="#cb50-2" tabindex="-1"></a>aov</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Y
##            Df Sum Sq Mean Sq F value Pr(&gt;F)
## X3          1   1254 1254.46  1.6127 0.2066
## Residuals 119  92564  777.85</code></pre>
<p><strong>R² Statistic</strong><br />
The R² statistic is approximately 0.013, implying that road width
explains only about 1.3% of the variation in AADT, suggesting that other
factors are more influential.</p>
<p>Summary</p>
<p>This analysis suggests that the width of a road section has a weak
and statistically insignificant relationship with AADT. While wider
roads generally allow for higher traffic volumes, this model does not
capture that effect effectively.</p>
</div>
<div id="x4" class="section level2">
<h2>X4</h2>
<p>Controlling access to the road section is one of the important
methods for improving traffic flow. In this chapter, we explore whether
this approach can effectively increase the annual average daily traffic.
We divide the data into two categories: the first category consists of
data where control measures are implemented, and the second category
consists of data without control measures. The distribution of these 2
categories</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" tabindex="-1"></a>X4_output_folder <span class="ot">&lt;-</span> <span class="fu">file.path</span>(slr_output_folder, <span class="st">&quot;X4&quot;</span>)</span>
<span id="cb52-2"><a href="#cb52-2" tabindex="-1"></a><span class="fu">dir.create</span>(X4_output_folder, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" tabindex="-1"></a><span class="co"># split data for X4 = 0 and X4 = 1</span></span>
<span id="cb53-2"><a href="#cb53-2" tabindex="-1"></a>y_control <span class="ot">&lt;-</span> data[data<span class="sc">$</span>X4 <span class="sc">==</span> <span class="dv">1</span>, <span class="st">&quot;Y&quot;</span>]</span>
<span id="cb53-3"><a href="#cb53-3" tabindex="-1"></a>y_no_control <span class="ot">&lt;-</span> data[data<span class="sc">$</span>X4 <span class="sc">==</span> <span class="dv">2</span>, <span class="st">&quot;Y&quot;</span>]</span></code></pre></div>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" tabindex="-1"></a>custom_colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;#2E86AB&quot;</span>, <span class="st">&quot;#A23B72&quot;</span>)</span>
<span id="cb54-2"><a href="#cb54-2" tabindex="-1"></a></span>
<span id="cb54-3"><a href="#cb54-3" tabindex="-1"></a>histogram_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(X4_output_folder, <span class="st">&quot;histogram.pdf&quot;</span>)</span>
<span id="cb54-4"><a href="#cb54-4" tabindex="-1"></a>histogram_X4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Y, <span class="at">fill =</span> <span class="fu">factor</span>(X4))) <span class="sc">+</span></span>
<span id="cb54-5"><a href="#cb54-5" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb54-6"><a href="#cb54-6" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb54-7"><a href="#cb54-7" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">30</span>,</span>
<span id="cb54-8"><a href="#cb54-8" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.8</span>,</span>
<span id="cb54-9"><a href="#cb54-9" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;white&quot;</span>,</span>
<span id="cb54-10"><a href="#cb54-10" tabindex="-1"></a>    <span class="at">size =</span> <span class="fl">0.2</span></span>
<span id="cb54-11"><a href="#cb54-11" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb54-12"><a href="#cb54-12" tabindex="-1"></a>  <span class="fu">geom_density</span>(</span>
<span id="cb54-13"><a href="#cb54-13" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">color =</span> <span class="fu">factor</span>(X4)),</span>
<span id="cb54-14"><a href="#cb54-14" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.2</span>,</span>
<span id="cb54-15"><a href="#cb54-15" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">1</span></span>
<span id="cb54-16"><a href="#cb54-16" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb54-17"><a href="#cb54-17" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb54-18"><a href="#cb54-18" tabindex="-1"></a>    <span class="at">title =</span> <span class="fu">TeX</span>(<span class="st">&quot;Distribution of $y&#39;$ across $x_4$&quot;</span>),</span>
<span id="cb54-19"><a href="#cb54-19" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">TeX</span>(<span class="st">&quot;$y&#39; = </span><span class="sc">\\</span><span class="st">log^2 y$&quot;</span>),</span>
<span id="cb54-20"><a href="#cb54-20" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Density&quot;</span>,</span>
<span id="cb54-21"><a href="#cb54-21" tabindex="-1"></a>    <span class="at">fill =</span> <span class="fu">TeX</span>(<span class="st">&quot;Category $x_4$&quot;</span>),</span>
<span id="cb54-22"><a href="#cb54-22" tabindex="-1"></a>    <span class="at">color =</span> <span class="fu">TeX</span>(<span class="st">&quot;Density Curve&quot;</span>)</span>
<span id="cb54-23"><a href="#cb54-23" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb54-24"><a href="#cb54-24" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb54-25"><a href="#cb54-25" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb54-26"><a href="#cb54-26" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(</span>
<span id="cb54-27"><a href="#cb54-27" tabindex="-1"></a>      <span class="at">size =</span> <span class="dv">16</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>,</span>
<span id="cb54-28"><a href="#cb54-28" tabindex="-1"></a>      <span class="at">margin =</span> <span class="fu">margin</span>(<span class="at">b =</span> <span class="dv">10</span>)</span>
<span id="cb54-29"><a href="#cb54-29" tabindex="-1"></a>    ),</span>
<span id="cb54-30"><a href="#cb54-30" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(</span>
<span id="cb54-31"><a href="#cb54-31" tabindex="-1"></a>      <span class="at">size =</span> <span class="dv">12</span>, <span class="at">color =</span> <span class="st">&quot;gray50&quot;</span>,</span>
<span id="cb54-32"><a href="#cb54-32" tabindex="-1"></a>      <span class="at">margin =</span> <span class="fu">margin</span>(<span class="at">b =</span> <span class="dv">20</span>)</span>
<span id="cb54-33"><a href="#cb54-33" tabindex="-1"></a>    ),</span>
<span id="cb54-34"><a href="#cb54-34" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb54-35"><a href="#cb54-35" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb54-36"><a href="#cb54-36" tabindex="-1"></a>    <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb54-37"><a href="#cb54-37" tabindex="-1"></a>    <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb54-38"><a href="#cb54-38" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">&quot;right&quot;</span>,</span>
<span id="cb54-39"><a href="#cb54-39" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb54-40"><a href="#cb54-40" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;gray90&quot;</span>),</span>
<span id="cb54-41"><a href="#cb54-41" tabindex="-1"></a>    <span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;white&quot;</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb54-42"><a href="#cb54-42" tabindex="-1"></a>    <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;white&quot;</span>, <span class="at">color =</span> <span class="cn">NA</span>)</span>
<span id="cb54-43"><a href="#cb54-43" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb54-44"><a href="#cb54-44" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> custom_colors, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Control&quot;</span>, <span class="st">&quot;No Control&quot;</span>)) <span class="sc">+</span></span>
<span id="cb54-45"><a href="#cb54-45" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> custom_colors, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Control&quot;</span>, <span class="st">&quot;No Control&quot;</span>))</span>
<span id="cb54-46"><a href="#cb54-46" tabindex="-1"></a></span>
<span id="cb54-47"><a href="#cb54-47" tabindex="-1"></a></span>
<span id="cb54-48"><a href="#cb54-48" tabindex="-1"></a><span class="fu">ggsave</span>(</span>
<span id="cb54-49"><a href="#cb54-49" tabindex="-1"></a>  histogram_path,</span>
<span id="cb54-50"><a href="#cb54-50" tabindex="-1"></a>  histogram_X4,</span>
<span id="cb54-51"><a href="#cb54-51" tabindex="-1"></a>  <span class="at">width =</span> <span class="dv">8</span>,</span>
<span id="cb54-52"><a href="#cb54-52" tabindex="-1"></a>  <span class="at">height =</span> <span class="dv">4</span>,</span>
<span id="cb54-53"><a href="#cb54-53" tabindex="-1"></a>)</span>
<span id="cb54-54"><a href="#cb54-54" tabindex="-1"></a></span>
<span id="cb54-55"><a href="#cb54-55" tabindex="-1"></a>histogram_X4</span></code></pre></div>
<p><img src="DataAnalysis_files/figure-html/unnamed-chunk-30-1.png" width="768" /></p>
<p>We can build the model</p>
<p><span class="math display">\[
\begin{aligned}
y&#39;_{ij} = \theta_i + \epsilon_{ij}, &amp;&amp; i \in \{1, 2\}, j \in
\left\{1, \cdots, n_i\right\}, &amp;&amp; \epsilon_{ij}\sim
\mathcal{N}\left(0, \sigma^2\right)
\end{aligned}
\]</span></p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" tabindex="-1"></a>theta_1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(y_control)</span>
<span id="cb55-2"><a href="#cb55-2" tabindex="-1"></a>theta_2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(y_no_control)</span>
<span id="cb55-3"><a href="#cb55-3" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;theta_1 = &quot;</span>, theta_1))</span></code></pre></div>
<pre><code>## [1] &quot;theta_1 =  114.097822707391&quot;</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;theta_2 = &quot;</span>, theta_2))</span></code></pre></div>
<pre><code>## [1] &quot;theta_2 =  70.4815506087082&quot;</code></pre>
<p>So</p>
<p><span class="math display">\[
\begin{cases}
  \hat{\theta}_1 = \overline{y_{1\cdot}}\approx 114.10 \\
  \hat{\theta}_2 = \overline{y_{2\cdot}}\approx 70.48
\end{cases}
\]</span></p>
<p>We build ANOVA table</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" tabindex="-1"></a>group_y <span class="ot">&lt;-</span> <span class="fu">c</span>(y_control, y_no_control)</span>
<span id="cb59-2"><a href="#cb59-2" tabindex="-1"></a>group <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rep</span>(</span>
<span id="cb59-3"><a href="#cb59-3" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;control&quot;</span>, <span class="st">&quot;no control&quot;</span>),</span>
<span id="cb59-4"><a href="#cb59-4" tabindex="-1"></a>  <span class="fu">c</span>(<span class="fu">length</span>(y_control), <span class="fu">length</span>(y_no_control))</span>
<span id="cb59-5"><a href="#cb59-5" tabindex="-1"></a>))</span>
<span id="cb59-6"><a href="#cb59-6" tabindex="-1"></a>anova_table <span class="ot">&lt;-</span> <span class="fu">aov</span>(group_y <span class="sc">~</span> group)</span>
<span id="cb59-7"><a href="#cb59-7" tabindex="-1"></a><span class="fu">summary</span>(anova_table)</span></code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## group         1  39903   39903   88.07 5.37e-16 ***
## Residuals   119  53916     453                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We calculate the p-value to be approximately 5.37 × 10⁻¹⁶. Since this
value is very small, we conclude that there is a significant difference
by controlling access to the road section.</p>
</div>
</div>
<div id="multiple-linear-regression" class="section level1">
<h1>Multiple Linear Regression</h1>
<p>As <span class="math inline">\(x_4\)</span> is a classification
variable, we create a dummy variable for it. So that <span
class="math inline">\(x_4 = 1\)</span> means we select the first class
(control) and <span class="math inline">\(x_4 = 0\)</span> means we
select the second class.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" tabindex="-1"></a><span class="do">### Full Model</span></span>
<span id="cb61-2"><a href="#cb61-2" tabindex="-1"></a></span>
<span id="cb61-3"><a href="#cb61-3" tabindex="-1"></a>mlr_output_folder <span class="ot">&lt;-</span> <span class="fu">file.path</span>(image_folder, <span class="st">&quot;mlr&quot;</span>)</span>
<span id="cb61-4"><a href="#cb61-4" tabindex="-1"></a><span class="fu">dir.create</span>(mlr_output_folder, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" tabindex="-1"></a>mlr <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2 <span class="sc">+</span> X3 <span class="sc">+</span> X4, <span class="at">data =</span> data)</span>
<span id="cb62-2"><a href="#cb62-2" tabindex="-1"></a><span class="fu">summary</span>(mlr)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y ~ X1 + X2 + X3 + X4, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -40.951  -7.647   0.037   8.356  32.947 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  53.739163   9.265768   5.800 5.85e-08 ***
## X1            0.036116   0.004247   8.503 7.38e-14 ***
## X2           11.069106   1.241316   8.917 8.11e-15 ***
## X3            0.018562   0.099140   0.187 0.851806    
## X4          -13.241270   3.604210  -3.674 0.000363 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 12.2 on 116 degrees of freedom
## Multiple R-squared:  0.8161, Adjusted R-squared:  0.8098 
## F-statistic: 128.7 on 4 and 116 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(mlr, data[, <span class="fu">c</span>(<span class="st">&quot;X1&quot;</span>, <span class="st">&quot;X2&quot;</span>, <span class="st">&quot;X3&quot;</span>, <span class="st">&quot;X4&quot;</span>)])</span></code></pre></div>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" tabindex="-1"></a>plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Y, <span class="at">y =</span> predicted)) <span class="sc">+</span></span>
<span id="cb65-2"><a href="#cb65-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb65-3"><a href="#cb65-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;y vs predicted values&quot;</span>) <span class="sc">+</span></span>
<span id="cb65-4"><a href="#cb65-4" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>)</span>
<span id="cb65-5"><a href="#cb65-5" tabindex="-1"></a></span>
<span id="cb65-6"><a href="#cb65-6" tabindex="-1"></a>file_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(</span>
<span id="cb65-7"><a href="#cb65-7" tabindex="-1"></a>  mlr_output_folder,</span>
<span id="cb65-8"><a href="#cb65-8" tabindex="-1"></a>  <span class="st">&quot;y_vs_predicted_values_full_model.pdf&quot;</span></span>
<span id="cb65-9"><a href="#cb65-9" tabindex="-1"></a>)</span>
<span id="cb65-10"><a href="#cb65-10" tabindex="-1"></a><span class="fu">ggsave</span>(file_path, plot, <span class="at">width =</span> <span class="dv">5</span>, <span class="at">height =</span> <span class="dv">5</span>)</span>
<span id="cb65-11"><a href="#cb65-11" tabindex="-1"></a>plot</span></code></pre></div>
<p><img src="DataAnalysis_files/figure-html/unnamed-chunk-36-1.png" width="480" /></p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" tabindex="-1"></a>plot_resid_mlr <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb66-2"><a href="#cb66-2" tabindex="-1"></a>  <span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">fitted =</span> <span class="fu">fitted</span>(mlr), <span class="at">residuals =</span> <span class="fu">resid</span>(mlr)),</span>
<span id="cb66-3"><a href="#cb66-3" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> fitted, <span class="at">y =</span> residuals)</span>
<span id="cb66-4"><a href="#cb66-4" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb66-5"><a href="#cb66-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;#1f78b4&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb66-6"><a href="#cb66-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb66-7"><a href="#cb66-7" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Fitted values&quot;</span>,</span>
<span id="cb66-8"><a href="#cb66-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Residuals&quot;</span>,</span>
<span id="cb66-9"><a href="#cb66-9" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Residuals vs Fitted&quot;</span></span>
<span id="cb66-10"><a href="#cb66-10" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb66-11"><a href="#cb66-11" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb66-12"><a href="#cb66-12" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">&quot;C&quot;</span>) <span class="sc">+</span></span>
<span id="cb66-13"><a href="#cb66-13" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb66-14"><a href="#cb66-14" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb66-15"><a href="#cb66-15" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb66-16"><a href="#cb66-16" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb66-17"><a href="#cb66-17" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>),</span>
<span id="cb66-18"><a href="#cb66-18" tabindex="-1"></a>  )</span>
<span id="cb66-19"><a href="#cb66-19" tabindex="-1"></a></span>
<span id="cb66-20"><a href="#cb66-20" tabindex="-1"></a>qqplot_mlr <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb66-21"><a href="#cb66-21" tabindex="-1"></a>  <span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">sample =</span> <span class="fu">resid</span>(mlr)),</span>
<span id="cb66-22"><a href="#cb66-22" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">sample =</span> sample)</span>
<span id="cb66-23"><a href="#cb66-23" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb66-24"><a href="#cb66-24" tabindex="-1"></a>  <span class="fu">stat_qq</span>(<span class="at">color =</span> <span class="st">&quot;#1f78b4&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb66-25"><a href="#cb66-25" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="at">color =</span> <span class="st">&quot;#e31a1c&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb66-26"><a href="#cb66-26" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb66-27"><a href="#cb66-27" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Theoretical Quantiles&quot;</span>,</span>
<span id="cb66-28"><a href="#cb66-28" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Sample Quantiles&quot;</span>,</span>
<span id="cb66-29"><a href="#cb66-29" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Normal Q-Q&quot;</span></span>
<span id="cb66-30"><a href="#cb66-30" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb66-31"><a href="#cb66-31" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb66-32"><a href="#cb66-32" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb66-33"><a href="#cb66-33" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb66-34"><a href="#cb66-34" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb66-35"><a href="#cb66-35" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb66-36"><a href="#cb66-36" tabindex="-1"></a>  )</span>
<span id="cb66-37"><a href="#cb66-37" tabindex="-1"></a></span>
<span id="cb66-38"><a href="#cb66-38" tabindex="-1"></a>mlr_res_fig <span class="ot">&lt;-</span> <span class="fu">grid.arrange</span>(plot_resid_mlr, qqplot_mlr, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="DataAnalysis_files/figure-html/unnamed-chunk-37-1.png" width="960" /></p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="fu">file.path</span>(mlr_output_folder, <span class="st">&quot;residuals_vs_fitted_qqplot.pdf&quot;</span>),</span>
<span id="cb67-2"><a href="#cb67-2" tabindex="-1"></a>  mlr_res_fig,</span>
<span id="cb67-3"><a href="#cb67-3" tabindex="-1"></a>  <span class="at">width =</span> <span class="dv">10</span>, <span class="at">height =</span> <span class="dv">4</span></span>
<span id="cb67-4"><a href="#cb67-4" tabindex="-1"></a>)</span></code></pre></div>
<div id="adjusted-full-model" class="section level2">
<h2>Adjusted Full Model</h2>
<p>Figure shows the model predictions and residuals. We observe that the
<span class="math inline">\(\sigma\)</span> of the residuals depends on
<span class="math inline">\(y&#39;\)</span>, indicating
heteroscedasticity. Therefore, we need to adjust the transformation to
make <span class="math inline">\(\sigma\)</span> constant.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" tabindex="-1"></a>data<span class="sc">$</span>Y <span class="ot">&lt;-</span> data<span class="sc">$</span>Y<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" tabindex="-1"></a>mlr_output_folder <span class="ot">&lt;-</span> <span class="fu">file.path</span>(image_folder, <span class="st">&quot;mlr&quot;</span>)</span>
<span id="cb69-2"><a href="#cb69-2" tabindex="-1"></a><span class="fu">dir.create</span>(mlr_output_folder, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" tabindex="-1"></a>mlr <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2 <span class="sc">+</span> X3 <span class="sc">+</span> X4, <span class="at">data =</span> data)</span>
<span id="cb70-2"><a href="#cb70-2" tabindex="-1"></a><span class="fu">summary</span>(mlr)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y ~ X1 + X2 + X3 + X4, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6033.4 -1170.8    56.4  1096.4  4883.4 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  4029.735   1348.156   2.989  0.00342 ** 
## X1              6.174      0.618   9.991  &lt; 2e-16 ***
## X2           1806.718    180.610  10.003  &lt; 2e-16 ***
## X3              3.421     14.425   0.237  0.81294    
## X4          -2876.276    524.407  -5.485 2.46e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1774 on 116 degrees of freedom
## Multiple R-squared:  0.8644, Adjusted R-squared:  0.8598 
## F-statistic: 184.9 on 4 and 116 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(mlr, data[, <span class="fu">c</span>(<span class="st">&quot;X1&quot;</span>, <span class="st">&quot;X2&quot;</span>, <span class="st">&quot;X3&quot;</span>, <span class="st">&quot;X4&quot;</span>)])</span></code></pre></div>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Y, <span class="at">y =</span> predicted)) <span class="sc">+</span></span>
<span id="cb73-2"><a href="#cb73-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb73-3"><a href="#cb73-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;y vs predicted values&quot;</span>) <span class="sc">+</span></span>
<span id="cb73-4"><a href="#cb73-4" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="DataAnalysis_files/figure-html/unnamed-chunk-42-1.png" width="480" /></p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" tabindex="-1"></a>plot_resid_mlr <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb74-2"><a href="#cb74-2" tabindex="-1"></a>  <span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">fitted =</span> <span class="fu">fitted</span>(mlr), <span class="at">residuals =</span> <span class="fu">resid</span>(mlr)),</span>
<span id="cb74-3"><a href="#cb74-3" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> fitted, <span class="at">y =</span> residuals)</span>
<span id="cb74-4"><a href="#cb74-4" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb74-5"><a href="#cb74-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;#1f78b4&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb74-6"><a href="#cb74-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb74-7"><a href="#cb74-7" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Fitted values&quot;</span>,</span>
<span id="cb74-8"><a href="#cb74-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Residuals&quot;</span>,</span>
<span id="cb74-9"><a href="#cb74-9" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Residuals vs Fitted&quot;</span></span>
<span id="cb74-10"><a href="#cb74-10" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb74-11"><a href="#cb74-11" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb74-12"><a href="#cb74-12" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">&quot;C&quot;</span>) <span class="sc">+</span></span>
<span id="cb74-13"><a href="#cb74-13" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb74-14"><a href="#cb74-14" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb74-15"><a href="#cb74-15" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb74-16"><a href="#cb74-16" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb74-17"><a href="#cb74-17" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>),</span>
<span id="cb74-18"><a href="#cb74-18" tabindex="-1"></a>  )</span>
<span id="cb74-19"><a href="#cb74-19" tabindex="-1"></a></span>
<span id="cb74-20"><a href="#cb74-20" tabindex="-1"></a>qqplot_mlr <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb74-21"><a href="#cb74-21" tabindex="-1"></a>  <span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">sample =</span> <span class="fu">resid</span>(mlr)),</span>
<span id="cb74-22"><a href="#cb74-22" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">sample =</span> sample)</span>
<span id="cb74-23"><a href="#cb74-23" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb74-24"><a href="#cb74-24" tabindex="-1"></a>  <span class="fu">stat_qq</span>(<span class="at">color =</span> <span class="st">&quot;#1f78b4&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb74-25"><a href="#cb74-25" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="at">color =</span> <span class="st">&quot;#e31a1c&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb74-26"><a href="#cb74-26" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb74-27"><a href="#cb74-27" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Theoretical Quantiles&quot;</span>,</span>
<span id="cb74-28"><a href="#cb74-28" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Sample Quantiles&quot;</span>,</span>
<span id="cb74-29"><a href="#cb74-29" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Normal Q-Q&quot;</span></span>
<span id="cb74-30"><a href="#cb74-30" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb74-31"><a href="#cb74-31" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb74-32"><a href="#cb74-32" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb74-33"><a href="#cb74-33" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb74-34"><a href="#cb74-34" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb74-35"><a href="#cb74-35" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb74-36"><a href="#cb74-36" tabindex="-1"></a>  )</span>
<span id="cb74-37"><a href="#cb74-37" tabindex="-1"></a></span>
<span id="cb74-38"><a href="#cb74-38" tabindex="-1"></a>mlr_res_fig <span class="ot">&lt;-</span> <span class="fu">grid.arrange</span>(plot_resid_mlr, qqplot_mlr, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="DataAnalysis_files/figure-html/unnamed-chunk-43-1.png" width="960" /></p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" tabindex="-1"></a><span class="fu">ggsave</span>(</span>
<span id="cb75-2"><a href="#cb75-2" tabindex="-1"></a>  <span class="fu">file.path</span>(</span>
<span id="cb75-3"><a href="#cb75-3" tabindex="-1"></a>    mlr_output_folder,</span>
<span id="cb75-4"><a href="#cb75-4" tabindex="-1"></a>    <span class="st">&quot;residuals_vs_fitted_qqplot_transformed.pdf&quot;</span></span>
<span id="cb75-5"><a href="#cb75-5" tabindex="-1"></a>  ),</span>
<span id="cb75-6"><a href="#cb75-6" tabindex="-1"></a>  mlr_res_fig,</span>
<span id="cb75-7"><a href="#cb75-7" tabindex="-1"></a>  <span class="at">width =</span> <span class="dv">10</span>, <span class="at">height =</span> <span class="dv">4</span></span>
<span id="cb75-8"><a href="#cb75-8" tabindex="-1"></a>)</span></code></pre></div>
<p>We succeed in the goal by doing the transformation <span
class="math inline">\(y&#39; = \log^4 y\)</span></p>
<p>So The model becomes: <span class="math display">\[
\log^4 y = \beta_0 + \beta_1 \sqrt{x_1} + \beta_2 x_2 + \beta_3 x_3 +
\beta_4 (2 - x_4) + \epsilon
\]</span></p>
</div>
<div id="adequacy-of-the-model" class="section level2">
<h2>Adequacy of the model</h2>
<p>To check the adequacy of the model, we build an ANOVA / ANCOVA table
for each variable. We can find that <span
class="math inline">\(x_1&#39;, x_2, x_4&#39;\)</span> have information
with <span class="math inline">\(y\)</span>, while <span
class="math inline">\(x_3\)</span> can be removed as it have a great
<span class="math inline">\(p\)</span>-value.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" tabindex="-1"></a>eliminate_x1_mlr <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X2 <span class="sc">+</span> X3 <span class="sc">+</span> X4, <span class="at">data =</span> data)</span>
<span id="cb76-2"><a href="#cb76-2" tabindex="-1"></a>eliminate_x2_mlr <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X3 <span class="sc">+</span> X4, <span class="at">data =</span> data)</span>
<span id="cb76-3"><a href="#cb76-3" tabindex="-1"></a>eliminate_x3_mlr <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2 <span class="sc">+</span> X4, <span class="at">data =</span> data)</span>
<span id="cb76-4"><a href="#cb76-4" tabindex="-1"></a>eliminate_x4_mlr <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2 <span class="sc">+</span> X3, <span class="at">data =</span> data)</span></code></pre></div>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" tabindex="-1"></a><span class="fu">anova</span>(eliminate_x1_mlr, mlr)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Y ~ X2 + X3 + X4
## Model 2: Y ~ X1 + X2 + X3 + X4
##   Res.Df       RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    117 679542372                                  
## 2    116 365252858  1 314289514 99.815 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" tabindex="-1"></a><span class="fu">anova</span>(eliminate_x2_mlr, mlr)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Y ~ X1 + X3 + X4
## Model 2: Y ~ X1 + X2 + X3 + X4
##   Res.Df       RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    117 680342805                                  
## 2    116 365252858  1 315089947 100.07 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" tabindex="-1"></a><span class="fu">anova</span>(eliminate_x3_mlr, mlr)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Y ~ X1 + X2 + X4
## Model 2: Y ~ X1 + X2 + X3 + X4
##   Res.Df       RSS Df Sum of Sq      F Pr(&gt;F)
## 1    117 365429973                           
## 2    116 365252858  1    177115 0.0562 0.8129</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" tabindex="-1"></a><span class="fu">anova</span>(eliminate_x4_mlr, mlr)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Y ~ X1 + X2 + X3
## Model 2: Y ~ X1 + X2 + X3 + X4
##   Res.Df       RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    117 459976649                                  
## 2    116 365252858  1  94723791 30.083 2.457e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>So we try to eliminate <span class="math inline">\(X_3\)</span>.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" tabindex="-1"></a>mlr <span class="ot">&lt;-</span> eliminate_x3_mlr</span></code></pre></div>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" tabindex="-1"></a><span class="fu">summary</span>(mlr)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y ~ X1 + X2 + X4, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6068.1 -1185.4    60.4  1121.5  4865.5 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  4079.1529  1326.5738   3.075  0.00262 ** 
## X1              6.1950     0.6093  10.168  &lt; 2e-16 ***
## X2           1811.5492   178.7319  10.136  &lt; 2e-16 ***
## X4          -2857.4933   516.2981  -5.535 1.94e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1767 on 117 degrees of freedom
## Multiple R-squared:  0.8644, Adjusted R-squared:  0.8609 
## F-statistic: 248.6 on 3 and 117 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(mlr, data)</span></code></pre></div>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" tabindex="-1"></a>plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Y, <span class="at">y =</span> predicted)) <span class="sc">+</span></span>
<span id="cb89-2"><a href="#cb89-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb89-3"><a href="#cb89-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;y vs predicted values&quot;</span>) <span class="sc">+</span></span>
<span id="cb89-4"><a href="#cb89-4" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>)</span>
<span id="cb89-5"><a href="#cb89-5" tabindex="-1"></a>file_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(</span>
<span id="cb89-6"><a href="#cb89-6" tabindex="-1"></a>  mlr_output_folder,</span>
<span id="cb89-7"><a href="#cb89-7" tabindex="-1"></a>  <span class="st">&quot;y_vs_predicted_values_reduced_model.pdf&quot;</span></span>
<span id="cb89-8"><a href="#cb89-8" tabindex="-1"></a>)</span>
<span id="cb89-9"><a href="#cb89-9" tabindex="-1"></a><span class="fu">ggsave</span>(file_path, plot, <span class="at">width =</span> <span class="dv">5</span>, <span class="at">height =</span> <span class="dv">5</span>)</span>
<span id="cb89-10"><a href="#cb89-10" tabindex="-1"></a>plot</span></code></pre></div>
<p><img src="DataAnalysis_files/figure-html/unnamed-chunk-52-1.png" width="480" /></p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" tabindex="-1"></a>plot_resid_mlr <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb90-2"><a href="#cb90-2" tabindex="-1"></a>  <span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">fitted =</span> <span class="fu">fitted</span>(mlr), <span class="at">residuals =</span> <span class="fu">resid</span>(mlr)),</span>
<span id="cb90-3"><a href="#cb90-3" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> fitted, <span class="at">y =</span> residuals)</span>
<span id="cb90-4"><a href="#cb90-4" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb90-5"><a href="#cb90-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;#1f78b4&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb90-6"><a href="#cb90-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb90-7"><a href="#cb90-7" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Fitted values&quot;</span>,</span>
<span id="cb90-8"><a href="#cb90-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Residuals&quot;</span>,</span>
<span id="cb90-9"><a href="#cb90-9" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Residuals vs Fitted&quot;</span></span>
<span id="cb90-10"><a href="#cb90-10" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb90-11"><a href="#cb90-11" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb90-12"><a href="#cb90-12" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">&quot;C&quot;</span>) <span class="sc">+</span></span>
<span id="cb90-13"><a href="#cb90-13" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb90-14"><a href="#cb90-14" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb90-15"><a href="#cb90-15" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb90-16"><a href="#cb90-16" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb90-17"><a href="#cb90-17" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>),</span>
<span id="cb90-18"><a href="#cb90-18" tabindex="-1"></a>  )</span>
<span id="cb90-19"><a href="#cb90-19" tabindex="-1"></a></span>
<span id="cb90-20"><a href="#cb90-20" tabindex="-1"></a>qqplot_mlr <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb90-21"><a href="#cb90-21" tabindex="-1"></a>  <span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">sample =</span> <span class="fu">resid</span>(mlr)),</span>
<span id="cb90-22"><a href="#cb90-22" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">sample =</span> sample)</span>
<span id="cb90-23"><a href="#cb90-23" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb90-24"><a href="#cb90-24" tabindex="-1"></a>  <span class="fu">stat_qq</span>(<span class="at">color =</span> <span class="st">&quot;#1f78b4&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb90-25"><a href="#cb90-25" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="at">color =</span> <span class="st">&quot;#e31a1c&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb90-26"><a href="#cb90-26" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb90-27"><a href="#cb90-27" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Theoretical Quantiles&quot;</span>,</span>
<span id="cb90-28"><a href="#cb90-28" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Sample Quantiles&quot;</span>,</span>
<span id="cb90-29"><a href="#cb90-29" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Normal Q-Q&quot;</span></span>
<span id="cb90-30"><a href="#cb90-30" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb90-31"><a href="#cb90-31" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb90-32"><a href="#cb90-32" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb90-33"><a href="#cb90-33" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb90-34"><a href="#cb90-34" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb90-35"><a href="#cb90-35" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb90-36"><a href="#cb90-36" tabindex="-1"></a>  )</span>
<span id="cb90-37"><a href="#cb90-37" tabindex="-1"></a></span>
<span id="cb90-38"><a href="#cb90-38" tabindex="-1"></a>mlr_res_fig <span class="ot">&lt;-</span> <span class="fu">grid.arrange</span>(plot_resid_mlr, qqplot_mlr, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="DataAnalysis_files/figure-html/unnamed-chunk-53-1.png" width="960" /></p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="fu">file.path</span>(mlr_output_folder, <span class="st">&quot;reduced_residuals_vs_fitted_qqplot.pdf&quot;</span>),</span>
<span id="cb91-2"><a href="#cb91-2" tabindex="-1"></a>  mlr_res_fig,</span>
<span id="cb91-3"><a href="#cb91-3" tabindex="-1"></a>  <span class="at">width =</span> <span class="dv">10</span>, <span class="at">height =</span> <span class="dv">4</span></span>
<span id="cb91-4"><a href="#cb91-4" tabindex="-1"></a>)</span></code></pre></div>
</div>
</div>
<div id="prediction" class="section level1">
<h1>Prediction</h1>
<div id="data" class="section level2">
<h2>Data</h2>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="dv">50000</span></span>
<span id="cb92-2"><a href="#cb92-2" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb92-3"><a href="#cb92-3" tabindex="-1"></a>x3 <span class="ot">&lt;-</span> <span class="dv">60</span></span>
<span id="cb92-4"><a href="#cb92-4" tabindex="-1"></a>x4 <span class="ot">&lt;-</span> <span class="dv">2</span></span></code></pre></div>
<p>Then we do transformation for every values:</p>
<p><span class="math display">\[
\begin{cases}
x_1&#39; = \sqrt{x_1} \\
x_4&#39; = 2 - x_4
\end{cases}
\]</span></p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(x1)</span>
<span id="cb93-2"><a href="#cb93-2" tabindex="-1"></a>x4 <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">-</span> x4</span></code></pre></div>
</div>
<div id="point-estimation" class="section level2">
<h2>Point Estimation</h2>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" tabindex="-1"></a>y_hat <span class="ot">&lt;-</span> <span class="fu">predict</span>(mlr, <span class="fu">data.frame</span>(<span class="at">X1 =</span> x1, <span class="at">X2 =</span> x2, <span class="at">X3 =</span> x3, <span class="at">X4 =</span> x4))</span></code></pre></div>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" tabindex="-1"></a>y_hat</span></code></pre></div>
<pre><code>##        1 
## 10899.05</code></pre>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" tabindex="-1"></a><span class="fu">exp</span>(y_hat<span class="sc">^</span>(<span class="dv">1</span> <span class="sc">/</span> <span class="dv">4</span>))</span></code></pre></div>
<pre><code>##        1 
## 27379.73</code></pre>
<p>We transform back</p>
<p><span class="math display">\[
\hat{y} = \exp\sqrt[4]{\hat{y}&#39;}
\]</span></p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" tabindex="-1"></a>y_hat <span class="ot">&lt;-</span> <span class="fu">exp</span>(y_hat<span class="sc">^</span>(<span class="dv">1</span> <span class="sc">/</span> <span class="dv">4</span>))</span></code></pre></div>
<div class="sourceCode" id="cb100"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" tabindex="-1"></a>y_hat</span></code></pre></div>
<pre><code>##        1 
## 27379.73</code></pre>
</div>
<div id="interval-estimation" class="section level2">
<h2>Interval Estimation</h2>
<p>Let’s try to get the 90% interval</p>
<div class="sourceCode" id="cb102"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.1</span></span>
<span id="cb102-2"><a href="#cb102-2" tabindex="-1"></a>interval <span class="ot">&lt;-</span> <span class="fu">predict</span>(mlr, <span class="fu">data.frame</span>(<span class="at">X1 =</span> x1, <span class="at">X2 =</span> x2, <span class="at">X3 =</span> x3, <span class="at">X4 =</span> x4),</span>
<span id="cb102-3"><a href="#cb102-3" tabindex="-1"></a>  <span class="at">interval =</span> <span class="st">&quot;confidence&quot;</span>, <span class="at">level =</span> <span class="dv">1</span> <span class="sc">-</span> alpha</span>
<span id="cb102-4"><a href="#cb102-4" tabindex="-1"></a>)</span>
<span id="cb102-5"><a href="#cb102-5" tabindex="-1"></a>interval</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 10899.05 9329.203 12468.89</code></pre>
<div class="sourceCode" id="cb104"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" tabindex="-1"></a>l <span class="ot">&lt;-</span> <span class="fu">exp</span>(interval[<span class="dv">2</span>]<span class="sc">^</span>(<span class="dv">1</span> <span class="sc">/</span> <span class="dv">4</span>))</span>
<span id="cb104-2"><a href="#cb104-2" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">exp</span>(interval[<span class="dv">3</span>]<span class="sc">^</span>(<span class="dv">1</span> <span class="sc">/</span> <span class="dv">4</span>))</span>
<span id="cb104-3"><a href="#cb104-3" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;(&quot;</span>, l, <span class="st">&quot;, &quot;</span>, r, <span class="st">&quot;)&quot;</span>))</span></code></pre></div>
<pre><code>## [1] &quot;( 18544.1422848705 ,  38836.9550734659 )&quot;</code></pre>
</div>
</div>
<div class="footnotes footnotes-end-of-document">
<hr />
<ol>
<li id="fn1"><p><a href="mailto:FPU001@e.ntu.edu.sg"
class="email">FPU001@e.ntu.edu.sg</a><a href="#fnref1"
class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p><a href="mailto:ZHAN0564@e.ntu.edu.sg"
class="email">ZHAN0564@e.ntu.edu.sg</a><a href="#fnref2"
class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p><a href="mailto:SH0005YI@e.ntu.edu.sg"
class="email">SH0005YI@e.ntu.edu.sg</a><a href="#fnref3"
class="footnote-back">↩︎</a></p></li>
<li id="fn4"><p><a href="mailto:FUYI0005@e.ntu.edu.sg"
class="email">FUYI0005@e.ntu.edu.sg</a><a href="#fnref4"
class="footnote-back">↩︎</a></p></li>
<li id="fn5"><p><a href="mailto:M220100@e.ntu.edu.sg"
class="email">M220100@e.ntu.edu.sg</a><a href="#fnref5"
class="footnote-back">↩︎</a></p></li>
</ol>
</div>
</div>

   
   
            
      

  <script>
    $(document).ready(function () {

			
 		
	    });
  </script>



    <!-- dynamically load mathjax for compatibility with self-contained -->
  <script>
    (function () {
	var script = document.createElement("script");
	script.type = "text/javascript";
	script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
	document.getElementsByTagName("head")[0].appendChild(script);
    })();
  </script>
  
</body>
</html>
